#!/usr/bin/env python3
"""
Plot RF-DETR training metrics stored in log.txt as generated by main.py.

Usage:
    python plot_metrics.py --log /path/to/log.txt --output metrics_plot.png
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Iterable, List, Sequence, Tuple

import matplotlib.pyplot as plt


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot RF-DETR training metrics")
    parser.add_argument(
        "--log",
        type=Path,
        required=True,
        help="Path to log.txt generated during training",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Where to save the resulting plot (defaults next to log file)",
    )
    return parser.parse_args()


def load_log(path: Path) -> List[dict]:
    entries: List[dict] = []
    with path.open() as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                entries.append(json.loads(line))
            except json.JSONDecodeError as exc:
                print(f"跳过无法解析的行: {exc}")
    return entries


def filter_series(xs: Sequence[float], ys: Sequence[float]) -> Tuple[List[float], List[float]]:
    filtered = [(x, y) for x, y in zip(xs, ys) if y is not None]
    if not filtered:
        return [], []
    fx, fy = zip(*filtered)
    return list(fx), list(fy)


def plot_training_curves(
    entries: Iterable[dict],
    output_path: Path,
) -> None:
    epochs = []
    train_loss = []
    val_loss = []
    ap_base = []
    ap50_base = []
    ar_base = []
    ap_ema = []
    ap50_ema = []
    ar_ema = []

    for entry in entries:
        epoch = entry.get("epoch")
        if epoch is None:
            continue
        epoch_num = epoch + 1  # epoch 从 0 开始计数，这里转成 1-based
        epochs.append(epoch_num)
        train_loss.append(entry.get("train_loss"))
        val_loss.append(entry.get("test_loss"))

        coco = entry.get("test_coco_eval_bbox")
        ema_coco = entry.get("ema_test_coco_eval_bbox")

        ap_base.append(coco[0] if coco else None)
        ap50_base.append(coco[1] if coco else None)
        ar_base.append(coco[8] if coco and len(coco) > 8 else None)

        ap_ema.append(ema_coco[0] if ema_coco else None)
        ap50_ema.append(ema_coco[1] if ema_coco else None)
        ar_ema.append(ema_coco[8] if ema_coco and len(ema_coco) > 8 else None)

    fig, axes = plt.subplots(2, 2, figsize=(16, 9), constrained_layout=True)

    ax = axes[0, 0]
    train_x, train_y = filter_series(epochs, train_loss)
    val_x, val_y = filter_series(epochs, val_loss)
    if train_x:
        ax.plot(train_x, train_y, marker="o", label="Training Loss")
    if val_x:
        ax.plot(val_x, val_y, marker="o", label="Validation Loss")
    ax.set_title("Training and Validation Loss")
    ax.set_xlabel("Epoch Number")
    ax.set_ylabel("Loss Value")
    ax.grid(True, linestyle="--", alpha=0.4)
    ax.legend()

    ax = axes[0, 1]
    base_x, base_y = filter_series(epochs, ap50_base)
    ema_x, ema_y = filter_series(epochs, ap50_ema)
    if base_x:
        ax.plot(base_x, base_y, marker="o", label="Base Model")
    if ema_x:
        ax.plot(ema_x, ema_y, marker="o", label="EMA Model")
    ax.set_title("Average Precision @0.50")
    ax.set_xlabel("Epoch Number")
    ax.set_ylabel("AP50")
    ax.grid(True, linestyle="--", alpha=0.4)
    ax.legend()

    ax = axes[1, 0]
    base_x, base_y = filter_series(epochs, ap_base)
    ema_x, ema_y = filter_series(epochs, ap_ema)
    if base_x:
        ax.plot(base_x, base_y, marker="o", label="Base Model")
    if ema_x:
        ax.plot(ema_x, ema_y, marker="o", label="EMA Model")
    ax.set_title("Average Precision @0.50:0.95")
    ax.set_xlabel("Epoch Number")
    ax.set_ylabel("AP")
    ax.grid(True, linestyle="--", alpha=0.4)
    ax.legend()

    ax = axes[1, 1]
    base_x, base_y = filter_series(epochs, ar_base)
    ema_x, ema_y = filter_series(epochs, ar_ema)
    if base_x:
        ax.plot(base_x, base_y, marker="o", label="Base Model")
    if ema_x:
        ax.plot(ema_x, ema_y, marker="o", label="EMA Model")
    ax.set_title("Average Recall @0.50:0.95")
    ax.set_xlabel("Epoch Number")
    ax.set_ylabel("AR")
    ax.grid(True, linestyle="--", alpha=0.4)
    ax.legend()

    fig.suptitle("RF-DETR Training Metrics", fontsize=16)
    fig.savefig(output_path, dpi=150)
    print(f"图像已保存到: {output_path}")


def main():
    args = parse_args()
    log_path: Path = args.log
    entries = load_log(log_path)
    if not entries:
        raise SystemExit(f"无法从 {log_path} 读取到有效的数据。")

    output_path = args.output
    if output_path is None:
        output_path = log_path.parent / "metrics_plot.png"
    else:
        output_path = output_path.resolve()
    plot_training_curves(entries, output_path)


if __name__ == "__main__":
    main()
